# Generated by Django 6.0.6 on 2026-06-05 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True, verbose_name='nome')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'categoria de material',
                'verbose_name_plural': 'categorias de materiais',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='código')),
                ('nome', models.CharField(max_length=255, verbose_name='nome')),
                ('tipo', models.CharField(choices=[('material', 'Material Hospitalar'), ('medicamento', 'Medicamento'), ('opme', 'OPME'), ('insumo', 'Insumo')], max_length=20, verbose_name='tipo')),
                ('unidade_medida', models.CharField(default='un', max_length=20, verbose_name='unidade de medida')),
                ('quantidade_estoque', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='quantidade em estoque')),
                ('estoque_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='estoque mínimo')),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='valor unitário')),
                ('observacoes', models.TextField(blank=True, default='', verbose_name='observações')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='materiais', to='materials.categoriamaterial', verbose_name='categoria')),
            ],
            options={
                'verbose_name': 'material',
                'verbose_name_plural': 'materiais',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='MovimentoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída'), ('ajuste', 'Ajuste')], max_length=10, verbose_name='tipo')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='quantidade')),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='valor unitário')),
                ('observacao', models.TextField(blank=True, default='', verbose_name='observação')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentos', to='materials.material', verbose_name='material')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'movimento de estoque',
                'verbose_name_plural': 'movimentos de estoque',
                'ordering': ['-created_at'],
            },
        ),
    ]
