# Generated by Django 6.0.6 on 2026-06-05 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faturamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('data_emissao', models.DateTimeField(auto_now_add=True, verbose_name='data de emissão')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('parcial', 'Parcialmente Pago'), ('pago', 'Pago'), ('cancelado', 'Cancelado')], default='pendente', max_length=20, verbose_name='status')),
                ('observacoes', models.TextField(blank=True, default='', verbose_name='observações')),
                ('convenio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.convenio', verbose_name='convênio')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faturamentos', to='patients.paciente', verbose_name='paciente')),
            ],
            options={
                'verbose_name': 'faturamento',
                'verbose_name_plural': 'faturamentos',
                'ordering': ['-data_emissao'],
            },
        ),
        migrations.CreateModel(
            name='ItemFaturamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('tipo', models.CharField(choices=[('sala', 'Utilização de Sala'), ('kit', 'Kit Cirúrgico'), ('material_extra', 'Material Extra'), ('medicamento', 'Medicamento'), ('taxa', 'Taxa Hospitalar'), ('procedimento', 'Procedimento'), ('outro', 'Outro')], max_length=20, verbose_name='tipo')),
                ('descricao', models.CharField(max_length=500, verbose_name='descrição')),
                ('quantidade', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='quantidade')),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor unitário')),
                ('cirurgia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_faturamento', to='scheduling.cirurgia', verbose_name='cirurgia')),
                ('faturamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='billing.faturamento', verbose_name='faturamento')),
            ],
            options={
                'verbose_name': 'item do faturamento',
                'verbose_name_plural': 'itens do faturamento',
                'ordering': ['tipo'],
            },
        ),
    ]
