# Generated by Django 6.0.6 on 2026-06-05 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfissionalEnfermagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('nome', models.CharField(max_length=255, verbose_name='nome')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('email', models.EmailField(blank=True, default='', max_length=255, verbose_name='e-mail')),
                ('telefone', models.CharField(blank=True, default='', max_length=20, verbose_name='telefone')),
                ('coren', models.CharField(max_length=20, unique=True, verbose_name='COREN')),
                ('funcao', models.CharField(choices=[('enfermeiro', 'Enfermeiro'), ('tecnico', 'Técnico de Enfermagem'), ('circulante', 'Circulante')], max_length=20, verbose_name='função')),
            ],
            options={
                'verbose_name': 'profissional de enfermagem',
                'verbose_name_plural': 'profissionais de enfermagem',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='EquipeCirurgia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('anestesista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cirurgias', to='doctors.anestesista', verbose_name='anestesista')),
                ('cirurgia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipe', to='scheduling.cirurgia', verbose_name='cirurgia')),
                ('cirurgiao_auxiliar_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cirurgias_aux1', to='doctors.cirurgiao', verbose_name='auxiliar 1')),
                ('cirurgiao_auxiliar_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cirurgias_aux2', to='doctors.cirurgiao', verbose_name='auxiliar 2')),
                ('circulante_atual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='circulacoes', to='team.profissionalenfermagem', verbose_name='circulante atual')),
                ('instrumentador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instrumentacoes', to='team.profissionalenfermagem', verbose_name='instrumentador')),
            ],
            options={
                'verbose_name': 'equipe da cirurgia',
                'verbose_name_plural': 'equipes das cirurgias',
            },
        ),
        migrations.CreateModel(
            name='RegistroPresenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('profissional_nome', models.CharField(max_length=255, verbose_name='nome do profissional')),
                ('funcao', models.CharField(max_length=50, verbose_name='função')),
                ('entrada', models.DateTimeField(verbose_name='entrada')),
                ('saida', models.DateTimeField(blank=True, null=True, verbose_name='saída')),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas', to='team.equipecirurgia', verbose_name='equipe')),
            ],
            options={
                'verbose_name': 'registro de presença',
                'verbose_name_plural': 'registros de presença',
                'ordering': ['entrada'],
            },
        ),
        migrations.CreateModel(
            name='TrocaPlantao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('data_hora_troca', models.DateTimeField(verbose_name='data/hora da troca')),
                ('observacao', models.TextField(blank=True, default='', verbose_name='observação')),
                ('circulante_entrada', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trocas_entrada', to='team.profissionalenfermagem', verbose_name='circulante que entrou')),
                ('circulante_saida', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trocas_saida', to='team.profissionalenfermagem', verbose_name='circulante que saiu')),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trocas_plantao', to='team.equipecirurgia', verbose_name='equipe')),
            ],
            options={
                'verbose_name': 'troca de plantão',
                'verbose_name_plural': 'trocas de plantão',
                'ordering': ['-data_hora_troca'],
            },
        ),
    ]
