# Generated by Django 6.0.6 on 2026-06-05 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('materials', '0001_initial'),
        ('patients', '0001_initial'),
        ('procedures', '0001_initial'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cirurgia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('data', models.DateField(verbose_name='data da cirurgia')),
                ('hora_inicio', models.TimeField(verbose_name='hora de início')),
                ('hora_prevista_termino', models.TimeField(verbose_name='hora prevista de término')),
                ('hora_inicio_real', models.TimeField(blank=True, null=True, verbose_name='hora de início real')),
                ('hora_termino_real', models.TimeField(blank=True, null=True, verbose_name='hora de término real')),
                ('status', models.CharField(choices=[('agendada', 'Agendada'), ('em_andamento', 'Em Andamento'), ('realizada', 'Realizada'), ('cancelada', 'Cancelada'), ('suspensa', 'Suspensa')], default='agendada', max_length=20, verbose_name='status')),
                ('observacoes', models.TextField(blank=True, default='', verbose_name='observações')),
                ('cirurgiao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cirurgias', to='doctors.cirurgiao', verbose_name='cirurgião principal')),
                ('convenio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.convenio', verbose_name='convênio')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cirurgias', to='patients.paciente', verbose_name='paciente')),
                ('procedimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cirurgias', to='procedures.procedimento', verbose_name='procedimento')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cirurgias', to='rooms.salacirurgica', verbose_name='sala')),
            ],
            options={
                'verbose_name': 'cirurgia',
                'verbose_name_plural': 'cirurgias',
                'ordering': ['-data', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='ConsumoMaterialCirurgia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='quantidade')),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor unitário')),
                ('is_extra', models.BooleanField(default=False, verbose_name='material extra')),
                ('observacao', models.TextField(blank=True, default='', verbose_name='observação')),
                ('cirurgia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiais_consumidos', to='scheduling.cirurgia', verbose_name='cirurgia')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumos_cirurgia', to='materials.material', verbose_name='material')),
            ],
            options={
                'verbose_name': 'consumo de material em cirurgia',
                'verbose_name_plural': 'consumos de materiais em cirurgias',
                'ordering': ['-created_at'],
            },
        ),
    ]
