# Generated by Django 6.0.6 on 2026-06-05 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitCirurgico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='código')),
                ('nome', models.CharField(max_length=255, verbose_name='nome')),
                ('descricao', models.TextField(blank=True, default='', verbose_name='descrição')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='valor total')),
            ],
            options={
                'verbose_name': 'kit cirúrgico',
                'verbose_name_plural': 'kits cirúrgicos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='KitItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('quantidade_padrao', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='quantidade padrão')),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='kits.kitcirurgico', verbose_name='kit')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kits', to='materials.material', verbose_name='material')),
            ],
            options={
                'verbose_name': 'item do kit',
                'verbose_name_plural': 'itens dos kits',
                'ordering': ['kit', 'material'],
                'unique_together': {('kit', 'material')},
            },
        ),
    ]
