# Generated by Django 6.0.6 on 2026-06-05 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Convenio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True, verbose_name='nome')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='código')),
                ('telefone', models.CharField(blank=True, default='', max_length=20, verbose_name='telefone')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'convênio',
                'verbose_name_plural': 'convênios',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('nome', models.CharField(max_length=255, verbose_name='nome')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('email', models.EmailField(blank=True, default='', max_length=255, verbose_name='e-mail')),
                ('telefone', models.CharField(blank=True, default='', max_length=20, verbose_name='telefone')),
                ('rg', models.CharField(blank=True, default='', max_length=20, verbose_name='RG')),
                ('profissao', models.CharField(blank=True, default='', max_length=255, verbose_name='profissão')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='data de nascimento')),
                ('numero_carteirinha', models.CharField(blank=True, default='', max_length=50, verbose_name='carteirinha')),
                ('convenio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes', to='patients.convenio', verbose_name='convênio')),
            ],
            options={
                'verbose_name': 'paciente',
                'verbose_name_plural': 'pacientes',
                'ordering': ['nome'],
            },
        ),
    ]
