# Generated by Django 6.0.6 on 2026-06-05 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materials', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Leito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('numero', models.CharField(max_length=10, unique=True, verbose_name='número')),
                ('ala', models.CharField(blank=True, default='', max_length=50, verbose_name='ala')),
                ('is_ocupado', models.BooleanField(default=False, verbose_name='ocupado')),
            ],
            options={
                'verbose_name': 'leito',
                'verbose_name_plural': 'leitos',
                'ordering': ['ala', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='Internacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('data_entrada', models.DateTimeField(verbose_name='data de entrada')),
                ('data_alta', models.DateTimeField(blank=True, null=True, verbose_name='data de alta')),
                ('motivo', models.TextField(blank=True, default='', verbose_name='motivo')),
                ('observacoes', models.TextField(blank=True, default='', verbose_name='observações')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='internacoes', to='patients.paciente', verbose_name='paciente')),
                ('leito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='internacoes', to='admissions.leito', verbose_name='leito')),
            ],
            options={
                'verbose_name': 'internação',
                'verbose_name_plural': 'internações',
                'ordering': ['-data_entrada'],
            },
        ),
        migrations.CreateModel(
            name='ConsumoInternacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='quantidade')),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor unitário')),
                ('observacao', models.TextField(blank=True, default='', verbose_name='observação')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumos_internacao', to='materials.material', verbose_name='material')),
                ('internacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos', to='admissions.internacao', verbose_name='internação')),
            ],
            options={
                'verbose_name': 'consumo da internação',
                'verbose_name_plural': 'consumos da internação',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RegistroClinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='data/hora')),
                ('descricao', models.TextField(verbose_name='descrição')),
                ('internacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_clinicos', to='admissions.internacao', verbose_name='internação')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'registro clínico',
                'verbose_name_plural': 'registros clínicos',
                'ordering': ['-data_hora'],
            },
        ),
    ]
