# Generated by Django 6.0.6 on 2026-06-05 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('nome', models.CharField(max_length=255, verbose_name='nome')),
                ('tipo', models.CharField(max_length=50, verbose_name='tipo')),
                ('config_json', models.JSONField(verbose_name='configuração')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'dashboard',
                'verbose_name_plural': 'dashboards',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('nome', models.CharField(max_length=255, verbose_name='nome')),
                ('chave', models.CharField(max_length=50, unique=True, verbose_name='chave')),
                ('descricao', models.TextField(blank=True, default='', verbose_name='descrição')),
                ('valor_atual', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='valor atual')),
                ('valor_anterior', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='valor anterior')),
                ('unidade', models.CharField(default='', max_length=20, verbose_name='unidade')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='data de atualização')),
            ],
            options={
                'verbose_name': 'indicador',
                'verbose_name_plural': 'indicadores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='InsightIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('tipo', models.CharField(choices=[('ocupacao', 'Análise de Ocupação'), ('financeiro', 'Análise Financeira'), ('estoque', 'Análise de Estoque'), ('gerencial', 'Relatório Gerencial')], max_length=20, verbose_name='tipo')),
                ('titulo', models.CharField(max_length=255, verbose_name='título')),
                ('descricao', models.TextField(verbose_name='descrição')),
                ('dados_json', models.JSONField(blank=True, null=True, verbose_name='dados')),
                ('data_referencia', models.DateField(verbose_name='data de referência')),
                ('gerado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='gerado por')),
            ],
            options={
                'verbose_name': 'insight de IA',
                'verbose_name_plural': 'insights de IA',
                'ordering': ['-created_at'],
            },
        ),
    ]
