# Generated by Django 6.0.6 on 2026-06-05 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anestesista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('nome', models.CharField(max_length=255, verbose_name='nome')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('email', models.EmailField(blank=True, default='', max_length=255, verbose_name='e-mail')),
                ('telefone', models.CharField(blank=True, default='', max_length=20, verbose_name='telefone')),
                ('crm', models.CharField(max_length=20, unique=True, verbose_name='CRM')),
                ('valor_hora', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='valor por hora')),
            ],
            options={
                'verbose_name': 'anestesista',
                'verbose_name_plural': 'anestesistas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True, verbose_name='nome')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='código')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'especialidade',
                'verbose_name_plural': 'especialidades',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Cirurgiao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('nome', models.CharField(max_length=255, verbose_name='nome')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('email', models.EmailField(blank=True, default='', max_length=255, verbose_name='e-mail')),
                ('telefone', models.CharField(blank=True, default='', max_length=20, verbose_name='telefone')),
                ('crm', models.CharField(max_length=20, unique=True, verbose_name='CRM')),
                ('valor_hora', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='valor por hora')),
                ('especialidades', models.ManyToManyField(blank=True, related_name='cirurgioes', to='doctors.especialidade', verbose_name='especialidades')),
            ],
            options={
                'verbose_name': 'cirurgião',
                'verbose_name_plural': 'cirurgiões',
                'ordering': ['nome'],
            },
        ),
    ]
