# Generated by Django 6.0.6 on 2026-06-05 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procedimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('nome', models.CharField(max_length=255, verbose_name='nome')),
                ('codigo_interno', models.CharField(max_length=20, unique=True, verbose_name='código interno')),
                ('codigo_tuss', models.CharField(blank=True, default='', max_length=20, verbose_name='código TUSS')),
                ('tempo_medio_previsto', models.DurationField(blank=True, null=True, verbose_name='tempo médio previsto')),
                ('valor_base', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='valor base')),
                ('observacoes', models.TextField(blank=True, default='', verbose_name='observações')),
                ('especialidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='procedimentos', to='doctors.especialidade', verbose_name='especialidade')),
            ],
            options={
                'verbose_name': 'procedimento',
                'verbose_name_plural': 'procedimentos',
                'ordering': ['nome'],
            },
        ),
    ]
