# Generated by Django 6.0.6 on 2026-06-05 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalaCirurgica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True, verbose_name='número')),
                ('nome', models.CharField(blank=True, default='', max_length=255, verbose_name='nome')),
                ('valor_hora', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor por hora')),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('ocupada', 'Ocupada'), ('manutencao', 'Em Manutenção'), ('reservada', 'Reservada')], default='disponivel', max_length=20, verbose_name='status')),
                ('observacoes', models.TextField(blank=True, default='', verbose_name='observações')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'sala cirúrgica',
                'verbose_name_plural': 'salas cirúrgicas',
                'ordering': ['numero'],
            },
        ),
    ]
